service: chessfunction

provider:
  name: aws
  runtime: python3.8
  memorySize: 128
  region: us-east-1
  timeout: 300
  lambdaHashingVersion: 20201221

  environment:
    DELIVERY_METHOD: 'email' # can be 'api' or 'email'
    RECIPIENT: 'your_receiving_email@example.com'
    SENDER: 'your_sending_email@example.com'
    REGION: ${self:provider.region}
    ANNOTATE_GAME: ${self:service}-${self:provider.stage}-annotate_game
    POST_API: 'https://api.yourdomain.com/api/yourendpoint' # your own api endpoint

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: 
        - "arn:aws:ses:${self:provider.region}:*:*"      
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource: "*"

package:
 include:
   - src/**
   - bin/**
 exclude:
   - parse.py
   - README.md
   - games/**
   - bin/stockfish-mac

functions:
  annotate_game:
    handler: src/handler.annotate_game
    memorySize: 1048
  annotate_games:
    handler: src/handler.annotate_games